<?php
/**
 * Created by PhpStorm.
 * User: chentsu
 * Date: 25.06.2016
 * Time: 15:18
 */

define('SITE_MAIN_LINK_TITLE','PHP 2 Урок 3 Недвижимость v0.2');

/** for controllers */
define('ERROR_SQL_INSERT', 'ERROR_SQL_INSERT');
define('ERROR_SQL_UPDATE', 'ERROR_SQL_UPDATE');
define('ERROR_SQL_DELETE', 'ERROR_SQL_DELETE');
define('ERROR_SQL_DELETE_CONSTRAINT', 'ERROR_SQL_DELETE_CONSTRAINT');


define('ERROR_ADD_REALTY','ERROR_ADD_REALTY');
define('ERROR_EDIT_REALTY','ERROR_EDIT_REALTY');
define("ERROR_DELETE_REALTY",'ERROR_DELETE_REALTY');

define('ERROR_ADD_OBJECT','ERROR_ADD_OBJECT');
define("ERROR_DELETE_OBJECT",'ERROR_DELETE_OBJECT');
define('ERROR_DELETE_OBJECT_CONSTRAINT', 'ERROR_DELETE_OBJECT_CONSTRAINT');
define('ERROR_EDIT_OBJECT','ERROR_EDIT_OBJECT');

define("REALTY_FILENAME_START", "realty-");
define("REALTY_TYPES_FILENAME_START", "realty_type-");
